# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180725_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='users/profile_pic'),
        ),
    ]
