# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 08:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180725_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='board_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_XII_board_name',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('WBSE', 'WBSE')], default='CBSE', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_XII_marksheet',
            field=models.ImageField(blank=True, upload_to='users/marksheetXII'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_XII_percentage',
            field=models.IntegerField(blank=True, default=40, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_XII_year_of_passing_or_expected',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_X_board_name',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('WBSE', 'WBSE')], default='ICSE', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_X_marksheet',
            field=models.ImageField(blank=True, upload_to='users/marksheetX'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_X_percentage',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_X_year_of_passing',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, default=9900000000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fresher_or_dropper',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Dropper', 'Dropper')], default='Fresher', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gardian_contact_number',
            field=models.IntegerField(default=9900000000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gardian_name',
            field=models.CharField(default='not given', max_length=40),
            preserve_default=False,
        ),
    ]
