# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 08:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180726_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_X_school_name',
            field=models.CharField(blank=True, help_text='Enter your School Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Optional'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_XII_board_name',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('WBSE', 'WBSE')], default='CBSE', help_text='Optional, Only in case of dropper', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_XII_marksheet',
            field=models.ImageField(blank=True, help_text='Optional, Only in case of dropper', upload_to='users/marksheetXII'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_XII_percentage',
            field=models.IntegerField(blank=True, default=40, help_text='Optional, Only in case of dropper', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_XII_year_of_passing_or_expected',
            field=models.DateField(blank=True, help_text='Optional, Only in case of dropper'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, help_text='Optional', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number_of_guardian',
            field=models.IntegerField(help_text='Required *', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='guardian_name',
            field=models.CharField(help_text='Father/Mother/Gaurdian Name', max_length=40),
        ),
    ]
