# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180726_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects_opted',
            field=models.CharField(choices=[('PCMB', 'PCMB'), ('PCM', 'PCM'), ('PCB', 'PCB')], default='PCB', help_text='P: Physics, C: Chemistry, M: Mathematics, B: Biology', max_length=5),
        ),
    ]
