# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 11:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180726_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='class_X_percentage',
            field=models.IntegerField(default=40, help_text='Enter the Integer Value', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)]),
        ),
    ]
