# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180726_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='class_XII_year_of_passing_or_expected',
            field=models.CharField(blank=True, choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], help_text='Optional, Only in case of dropper', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_X_year_of_passing',
            field=models.CharField(choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=5),
        ),
    ]
