# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 17:51
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190902_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Computer Sc.', 'Computer Sc.'), ('History/Geography', 'History/Geography'), ('Second Language', 'Second Language'), ('Others', 'Others')], default='Physics', max_length=91),
        ),
    ]
