# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-02 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=300)),
                ('exam_type', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Exam')),
            ],
        ),
    ]
