# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Computer', 'Computer'), ('Others', 'Others')], default='Others', max_length=40)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(default=datetime.datetime.now)),
                ('teacher', models.CharField(choices=[('Piyali Chakraborty', 'Piyali Chakraborty'), ('Rajesh Nag', 'Rajesh Nag'), ('Kamalendu Dalal', 'Kamalendu Dalal'), ('Suvendu saha', 'Suvendu saha'), ('Subrata Sarkar', 'Subrata Sarkar'), ('Tapan Dutta', 'Tapan Dutta')], max_length=90)),
                ('note', models.FileField(upload_to='./notes')),
            ],
        ),
    ]
