# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180705_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FileField(upload_to='notes'),
        ),
    ]
