# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180705_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FileField(upload_to='media/notes/'),
        ),
    ]
