# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180705_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
