# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-02 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180705_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Computer Sc.', 'Computer Sc.'), ('History/Geography', 'History/Geography'), ('Second Language', 'Second Language'), ('Others', 'Others')], default='Others', max_length=40),
        ),
    ]
