# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20190902_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='for_class',
            field=models.IntegerField(default=10, max_length=50),
        ),
    ]
