# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_for_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.URLField(default='/', help_text='Please Enter the URL here(GDrive/Amazon Drive)'),
        ),
    ]
