# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20200118_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.URLField(default='/', help_text='Please Enter the URL here(GDrive/Amazon Drive)', max_length=2000),
        ),
    ]
