# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ctype',
            field=models.CharField(choices=[('E', 'Engineering'), ('M', 'Medical')], default='E', max_length=1),
        ),
    ]
