# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_ctype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ctype',
            new_name='Type',
        ),
    ]
