# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180515_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Type',
            field=models.CharField(choices=[('cogs', 'Engineering'), ('stethoscope', 'Medical')], default='cogs', max_length=1),
        ),
    ]
