# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180515_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Computer', 'Computer')], default='Mathematics', max_length=20)),
                ('details', models.CharField(max_length=1000)),
                ('image', stdimage.models.StdImageField(upload_to='base/image/team')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='details',
            field=models.CharField(max_length=1200),
        ),
    ]
