# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180516_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to='static/base/img/gallery')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('Computer', 'Computer')], default='Mathematics', max_length=20)),
                ('descriptions', models.CharField(max_length=500)),
            ],
        ),
    ]
