# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 05:54
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20180705_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=stdimage.models.StdImageField(upload_to='img/gallery'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=stdimage.models.StdImageField(upload_to='img/team'),
        ),
    ]
