# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190902_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.URLField(help_text='Please Enter the URL to photo here (GDrive/Amazon Drive/Facebook)'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.URLField(help_text='Please Enter the URL here(GDrive/Amazon Drive/Facebook)'),
        ),
    ]
